# Copyright 2021 pguimaraes
# See LICENSE file for licensing details.
options:
  distro:
    default: 'confluent'
    type: string
    description: |
      Only two values possible: apache or confluent. Defines if will use apache kafka
      or confluent distro to install kafka packages. Both distro and version
      should be set.
  version:
    default: '6.1'
    type: string
    description: |
      Sets the kafka version for the given distro.
  keystore-path:
    default: ''
    type: string
    description: |
      Path to the keystore
  truststore-path:
    default: ''
    type: string
    description: |
      Path to the truststore
  regenerate-keystore-truststore:
    default: False
    type: boolean
    description: |
      If set to True, force charm to regenerate trust and keystore
  ssl_mutual_auth_enabled:
    default: False
    type: boolean
    description: |
      EXPERIMENTAL: this setting is still not enabled by default
  ssl_ca:
    default: ''
    type: string
    description: |
      CA certificate chain in base64
  ssl_cert:
    default: ''
    type: string
    description: |
      Certificate with CA certificate chain to be used in base64
  ssl_key:
    default: ''
    type: string
    description: |
      Key to be used in base64
  zookeeper-user:
    default: 'cp-kafka'
    type: string
    description: |
      User set for kafka broker services
  zookeeper-group:
    default: 'confluent'
    type: string
    description: |
      Group set for kafka broker services
  clientPort:
    type: int
    default: 2182
    description: |
      Port to be used to listen for client connections.
      If ssl_cert is specified or certificate relation enabled, then this port is
      configured as secureClientPort instead
  data-dir:
    type: string
    default: "/var/lib/zookeeper"
    description: |
      Folder to be used for zookeeper data.
  zookeeper-properties:
    type: string
    description: |
      Settings to be added to zookeeper.properties file.
      YAML formatted list of items
    default:
      maxClientCnxns: 0
      initLimit: 5
      syncLimit: 2
      autopurge.snapRetainCount: 10
      autopurge.purgeInterval: 1
      admin.enableServer: false
      
    
